# Site
name: "FasCin"
title: "FasCin"
description: "Il blog del Gruppo MARE, dove tutto fa...scena"
logo: 'assets/images/fclogo.jpg'
favicon: 'assets/images/fclogo.jpg'
baseurl: ''
google_analytics: 'G-V3NVEBMB82'
disqus: ''
include: ["_pages"]
permalink: /:title/
future: true
verbose: true

# Authors
authors:
  roberto:
    name: Roberto
    display_name: Roberto
    avatar: 'assets/images/Robetar.jpg'
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: roberto@gmail.com
    description: "tra mezz'ora giochiamo, ci sei? Ovvio. Cos'ha da offrire il mondo oltre il calcio? Un bel gateau di patate e sono felice"
  abele:
    name: Abele
    display_name: Abele
    avatar: 'assets/images/Abetar.jpg'
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: abelesanzari@gmail.com
    description: "Ingegnere, artista, scrittore, filantropo, cantante. Fa tutto, ma male."
  maria:
    name: Maria
    display_name: Maria
    avatar: 'assets/images/Mariatar.jpg'
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: mariarea@gmail.com
    description: "ragazza non ordinaria, tra le altre cose, amante della moda"
  elena:
    name: Elena
    display_name: Elena
    avatar: 'assets/images/Eletar.jpg'
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: elenadalponte@gmail.com
    description: "Parola d'ordine: Fatturare!"
  

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
